### ISSUE TITLE
post-up hook and STACK_INSTALL 

### ISSUE THREAD

**Issue by pablox-cl** [pbrisbin/dotfiles#1]
I just tried to clone the dotfiles on an entire new machine, and I found that the post-up fails with

    stack command not found

Looking at the `post-up`, it seems that the `"${STACK_INSTALL:-1}"` is failing because running that command results in:

    zsh: command not found: 1

I'm using 

    zsh 5.1.1 (x86_64-ubuntu-linux-gnu)

**Comment by pablox-cl** [comment]
Maybe [line 16](https://github.com/pbrisbin/dotfiles/blob/f0b4e70c8a04eaba11b85ceac0679c356f619dff/hooks/post-up#L16) could be changed to:

    if (( ${+STACK_INSTALL} )); then

But I believe that assumes `zsh`, so this could be simpler:

    if [ -n "$STACK_INSTALL" ]; then

**Comment by pbrisbin** [comment]
It's expected that you would see `stack command not found` because the default is `=1`. You will want to do `STACK_INSTALL=0 rcup`.

The `zsh: command not found: 1` is a red herring. You would see that if you just ran the bare expression `"${STACK_INSTALL:-1}"` because that's equivalent to just typing `1` at your prompt, which is not a command.

Your `-n` alternatively would work but is different behavior as I'm using a value of `1` to mean `true` and any other value to mean false. What you've got would use any non-empty value to mean `true`.

Hope that helps sort things out!

```sh
sh-4.4$ unset STACK_INSTALL
sh-4.4$ if [ "${STACK_INSTALL:-1}" -eq 1 ]; then echo "STACK_INSTALL is 1"; fi
STACK_INSTALL is 1
sh-4.4$ STACK_INSTALL=0
sh-4.4$ if [ "${STACK_INSTALL:-1}" -eq 1 ]; then echo "STACK_INSTALL is 1"; fi
sh-4.4$ 
```
